import { Navbar } from '@/components'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} content-grid font-satoshi`}>
				<header className='content-grid fixed z-50 w-full bg-white border-b border-black/10'>
					<Navbar />
				</header>
				<main className='pt-28 pl-5 pr-5 bg-slate-100'>{children}</main>
			</body>
		</html>
	)
}
